---
- name: "[MONITORING] create loki data directory"
  file:
    path: "{{ loki_db_dir }}"
    state: directory
    owner: 1000   
    group: 1000
    mode: 0755
  become: true

- name: "[MONITORING] create loki config directory"
  file:
    path: "{{ loki_config_dir }}"
    state: directory
    owner: 1000
    group: 1000
    mode: 0755
  become: true

- name: "[MONITORING] copy loki config"
  template:
    src: "{{ role_path }}/files/etc/loki/loki.yml.j2"
    dest: "{{ loki_config_dir }}/loki.yml"
    owner: 1000
    group: 1000
    mode: 0644
  become: true

- name: "[MONITORING] run Loki container"
  community.docker.docker_container:
    name: loki
    image: "grafana/loki:{{ loki_version }}"
    state: started
    restart_policy: always
    networks:
      - name: monitoring_net
    user: root
    published_ports:
      - "127.0.0.1:{{ loki_net.port }}:{{ loki_net.port }}"
    volumes:
      - "{{ loki_config_dir }}:/etc/loki"
      - "{{ loki_db_dir }}:/loki"
    command: -config.file=/etc/loki/loki.yml
  become: true
