---
- name: create monitoring network
  community.docker.docker_network:
    name: monitoring_net
    state: present
  become: true

- name: "[MONITORING] Install Loki"
  include_tasks: install_loki.yml

- name: "[MONITORING] Install Grafana"
  include_tasks: install_grafana.yml