image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 1Gi

secrets:
  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
