---
- name: "[NGINX] Deploy API site config (HTTP only)"
  become: yes
  template:
    src: site_api.conf.j2
    dest: /etc/nginx/sites-available/{{ nginx_proxy_api_domain }}.conf
    mode: '0644'
  notify: Reload nginx

- name: "[NGINX] Enable API site"
  become: yes
  file:
    src: /etc/nginx/sites-available/{{ nginx_proxy_api_domain }}.conf
    dest: /etc/nginx/sites-enabled/{{ nginx_proxy_api_domain }}.conf
    state: link
  notify: Reload nginx

- name: "[NGINX] Deploy APP site config (HTTP only)"
  become: yes
  template:
    src: site_app.conf.j2
    dest: /etc/nginx/sites-available/{{ nginx_proxy_app_domain }}.conf
    mode: '0644'
  notify: Reload nginx

- name: "[NGINX] Enable APP site"
  become: yes
  file:
    src: /etc/nginx/sites-available/{{ nginx_proxy_app_domain }}.conf
    dest: /etc/nginx/sites-enabled/{{ nginx_proxy_app_domain }}.conf
    state: link
  notify: Reload nginx
