
---
- name: "[NGINX] Obtain/renew SSL certificate for API + APP domains"
  become: true
  command: >
    certbot --nginx
    -n --agree-tos
    -m {{ nginx_proxy_letsencrypt_email }}
    -d {{ nginx_proxy_api_domain }}
    -d {{ nginx_proxy_app_domain }}
    --redirect
    --non-interactive
  notify: Reload nginx

- name: "[NGINX] Ensure certbot.timer is enabled and active"
  become: true
  ansible.builtin.systemd:
    name: certbot.timer
    enabled: true
    state: started
