apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.fullname" . }}-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secrets.POSTGRES_DB | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}
