image:
  repository: ghcr.io/yasminekharrat123/jules-backend
  tag: "production"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 3001

imagePullSecrets:
  name: ghcr-secret

env:
  API__API_PORT: ""
  API__PAGINATION__PAGE_SIZE: 20
  API__CORS__ALLOWED_HOST_JSON: "[]"
  SEED__USERS__COUNT: 50

secrets:
  DB__DB_URI: ""

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
