---
- name: "[APP] Copy backend env file"
  template:
    src: "{{ app_backend_env_template }}"
    dest: "{{ app_backend_env_file }}"
    mode: "{{ app_env_file_mode }}"

- name: "[APP] Copy frontend env file"
  template:
    src: "{{ app_frontend_env_template }}"
    dest: "{{ app_frontend_env_file }}"
    mode: "{{ app_env_file_mode }}"

- name: "[APP] Run backend container"
  become: true
  community.docker.docker_container:
    name: "{{ app_backend_container_name }}"
    image: "{{ docker_registry }}/{{ docker_registry_user }}/{{ app_name }}-backend:{{ env }}"
    env_file: "{{ app_backend_env_file }}"
    ports:
      - "{{ api_port }}:{{ api_port }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ app_network_name }}"
    log_driver: loki
    log_options:
      loki-url: "http://{{ loki_net.fqdn }}:{{ loki_net.port }}/loki/api/v1/push"
      loki-external-labels: "app=backend,env={{ env }}"
    pull: yes

- name: "[APP] Run migration (one-shot)"
  become: true
  community.docker.docker_container:
    name: "{{ app_migrate_container_name }}"
    image: "{{ docker_registry }}/{{ docker_registry_user }}/{{ app_name }}-backend:{{ env }}"
    env_file: "{{ app_backend_env_file }}"
    command: "{{ app_migrate_command }}"
    restart_policy: "no"
    state: started
    auto_remove: yes
    networks:
      - name: "{{ app_network_name }}"
    log_driver: loki
    log_options:
      loki-url: "http://{{ loki_net.fqdn }}:{{ loki_net.port }}/loki/api/v1/push"
      loki-external-labels: "app=backend-migrate,env={{ env }}"
    pull: yes

- name: "[APP] Run frontend container"
  become: true
  community.docker.docker_container:
    name: "{{ app_frontend_container_name }}"
    image: "{{ docker_registry }}/{{ docker_registry_user }}/{{ app_name }}-frontend:{{ env }}"
    env_file: "{{ app_frontend_env_file }}"
    ports:
      - "{{ frontend_port }}:{{ frontend_port }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ app_network_name }}"
    log_driver: loki
    log_options:
      loki-url: "http://{{ loki_net.fqdn }}:{{ loki_net.port }}/loki/api/v1/push"
      loki-external-labels: "app=frontend,env={{ env }}"
    pull: yes
