apiVersion: v2
name: jules
description: Umbrella chart for Jules app (api + frontend + db)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: api
    version: 0.1.0
    repository: "file://../api"
  - name: frontend
    version: 0.1.0
    repository: "file://../frontend"
  - name: db
    version: 0.1.0
    repository: "file://../db"
