## For env files

# API
api_port: "{{ API_PORT | default('3001', true) }}"
api_page_size: "{{ API_PAGINATION_PAGE_SIZE }}"
seed_users_count: "{{ SEED_USERS_COUNT }}"
api_cors_json: "{{ API_CORS_JSON }}"

# Frontend
next_public_api_url: "{{ NEXT_PUBLIC_API_URL }}"




## For docker compose

# Backend
app_backend_env_template: "api.env.j2"
app_backend_env_file: "/home/{{ ansible_user }}/api.env"
app_backend_container_name: "{{ app_name }}-backend"
app_backend_depends_on:
  - "{{ postgres_container_name }}"


# Migration
app_migrate_container_name: "{{ app_name }}-migrate"
app_migrate_command: >
  sh -c "pnpm kysely migrate:latest && pnpm kysely seed:run"

# Frontend
app_frontend_env_template: "web.env.j2"
app_frontend_env_file: "/home/{{ ansible_user }}/web.env.local"
app_frontend_container_name: "{{ app_name }}-frontend"
app_frontend_port: "{{ APP_FRONT_PORT | default('3000', true) }}"
app_frontend_depends_on:
  - "{{ app_backend_container_name }}"

# General
app_env_file_mode: '0600'
docker_registry: "{{ DOCKER_REGISTRY }}"
docker_registry_user : "{{ DOCKER_REGISTRY_USER }}"

