replicaCount: 1

image:
  repository: ghcr.io/yasminekharrat123/jules-frontend
  tag: "production"
  pullPolicy: Always

imagePullSecrets:
  name: ghcr-secret

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: test-app.local
  path: /
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

livenessProbe:
  path: /
  port: "" 
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /
  port: ""
  initialDelaySeconds: 5
  periodSeconds: 5

env:
  NEXT_PUBLIC_API_URL: ""  

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

secrets: {}
