apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "api.name" . }}
  template:
    metadata:
      annotations:
        redeployTimestamp: "{{ now | unixEpoch }}"
      labels:
        app: {{ include "api.name" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      initContainers:
        - name: migrate-db-in-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sh", "-c"]
          args:
            - "pnpm kysely migrate:latest && pnpm kysely seed:run"
          env:
            {{- include "api.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- include "api.env" . | nindent 12 }}
