name: Build and Push App Docker Images

on:
  push:
    branches: ["master"]
    paths:
      - "web/**"
      - "api/**"
      - .github/workflows/app-docker-build.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [backend, frontend]
        include:
          - service: backend
            context: ./api
            path_filter: 'api/**'
          - service: frontend
            context: ./web
            path_filter: 'web/**'


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set short git commit SHA
        id: vars
        run: |
            calculatedSha=$(git rev-parse --short ${{ github.sha }})
            echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - name: Check if service changed
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            service:
              - ${{ matrix.path_filter }}

      - name: Build and push ${{ matrix.service }} image
        if: steps.changes.outputs.service == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ghcr.io/${{ secrets.DOCKER_REGISTRY_USER }}/${{ vars.APP_NAME }}-${{ matrix.service }}:${{ vars.ENV }}
            ghcr.io/${{ secrets.DOCKER_REGISTRY_USER }}/${{ vars.APP_NAME }}-${{ matrix.service }}:${{ env.COMMIT_SHORT_SHA }}
          build-args: ${{ matrix.service == 'frontend' && format('NEXT_PUBLIC_API__URL={0}', vars.NEXT_PUBLIC_API_URL) || '' }}
