name: CI

on:
  push:

jobs:
  checks:
    name: Run checks for Backend and Frontend
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        include:
          - service: backend
            context: ./api
          - service: frontend
            context: ./web
    defaults:
      run:
        working-directory: ${{ matrix.context }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run check:all
        run: pnpm run check:all

  docker-scan:
    name: Scan GHCR Docker images with Trivy
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        include:
          - service: backend
            context: ./api
          - service: frontend
            context: ./web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REGISTRY_USER }}/${{ vars.APP_NAME }}-${{ matrix.service }}:${{ vars.ENV }}

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REGISTRY_USER }}/${{ vars.APP_NAME }}-${{ matrix.service }}:${{ vars.ENV }}
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
