name: Deploy App with Ansible

on:
  workflow_run:
    workflows: ["Build and Push App Docker Images"]
    types:
      - completed
  workflow_dispatch:  # manual triggering

jobs:
  deploy:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

          docker run --rm \
            -v "${{ github.workspace }}/ansible:/ansible" \
            -v ~/.ssh:/root/.ssh:ro \
            -w /ansible \
            ghcr.io/${{ secrets.DOCKER_REGISTRY_USER }}/ansible:${{ vars.ENV }} \
            ansible-playbook -i inventory/hosts.yml deploy-app.yml --tags deploy-app \
            -e "DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}" \
            -e "DOCKER_REGISTRY_USER=${{ secrets.DOCKER_REGISTRY_USER }}" \
            -e "DOCKER_REGISTRY_PASSWORD=${{ secrets.DOCKER_REGISTRY_PASSWORD }}" \
            -e "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" \
            -e "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" \
            -e "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" \
            -e "POSTGRES_PORT=${{ vars.POSTGRES_PORT }}" \
            -e "API_CORS_JSON=${{ vars.API_CORS_JSON }}" \
            -e "API_PAGINATION_PAGE_SIZE=${{ vars.API_PAGINATION_PAGE_SIZE }}" \
            -e "API_PORT=${{ vars.API_PORT }}" \
            -e "APP_NAME=${{ vars.APP_NAME }}" \
            -e "ENV=${{ vars.ENV }}" \
            -e "NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}" \
            -e "SEED_USERS_COUNT=${{ vars.SEED_USERS_COUNT }}" \
            -e "APP_FRONT_PORT=${{ vars.APP_FRONT_PORT }}"