name: Build and Push Docker Images

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [backend, frontend]
        include:
          - service: backend
            context: ./api
          - service: frontend
            context: ./web
            build_args: |
              NEXT_PUBLIC_API__URL=${{ vars.NEXT_PUBLIC_API__URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set short git commit SHA
        id: vars
        run: |
            calculatedSha=$(git rev-parse --short ${{ github.sha }})
            echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: |
            ghcr.io/${{ secrets.DOCKER_REGISTRY_USER }}/${{ vars.APP_NAME }}-${{ matrix.service }}:latest
            ghcr.io/${{ secrets.DOCKER_REGISTRY_USER }}/${{ vars.APP_NAME }}-${{ matrix.service }}:${{ env.COMMIT_SHORT_SHA }}
          build-args: ${{ matrix.build_args || '' }}